version: "3.8"

services:
    app:
        command: [ "/project/docker/app.sh" ]
        build:
          context: .
          dockerfile: Dockerfile
        container_name: "app"
        depends_on:
          - db
        env_file:
          - .env
        environment:
          - MONGODB_URL=mongodb://mongo_db
        networks:
        - custom
    db:
        container_name: "mongo_db"
        image: mongo
        restart: on-failure
        ports:
            - "27017:27017"
        volumes:
          - /var/lib/mongodb/:/data/db
        networks:
        - custom
networks:
  custom:
    driver: bridge